name: clean_architecture_example
description: "Clean architecture used"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.1
  path: ^1.8.3

  http: ^1.1.2
  sqflite: ^2.3.0

  equatable: ^2.0.5

  flutter_bloc: ^8.1.3

  dartz: ^0.10.1
  get_it: ^8.0.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/